version: '3.8'

services:
  
  #Backend API
  backend:
    container_name: backend
    build: ./
    command: npm start -- -L
    working_dir: /usr/src/smart-brain-x1-api
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/smart-brain-x1-api

  #Postgres DB
  postgres:
    build: ./postgres
    env_file: .env
    ports:
      - "5432:5432" 

