version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  build-and-test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build Docker image
          command: |
            docker build -t smart-brain-x1-dockerize:circleci .
            docker images
workflows:
  build-test-deploy:
    jobs:
      - build-and-test